// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt__QLmrHrbZv9UdZ3rhqIpJUMMG-J8XI',
    appId: '1:564628828414:web:725b2c00e9d634cce635af',
    messagingSenderId: '564628828414',
    projectId: 'sanofinalproject',
    authDomain: 'sanofinalproject.firebaseapp.com',
    storageBucket: 'sanofinalproject.firebasestorage.app',
    measurementId: 'G-JKKE25FV00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRfBurklgGsOzqnEPpmbLT6_oxdLIuaZg',
    appId: '1:564628828414:android:0637db39fce23fa7e635af',
    messagingSenderId: '564628828414',
    projectId: 'sanofinalproject',
    storageBucket: 'sanofinalproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJOkWktkesVOOm_LkCa-pW905yZV5f8Fw',
    appId: '1:564628828414:ios:9e32fbbf72201cc9e635af',
    messagingSenderId: '564628828414',
    projectId: 'sanofinalproject',
    storageBucket: 'sanofinalproject.firebasestorage.app',
    iosBundleId: 'com.example.sanoFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJOkWktkesVOOm_LkCa-pW905yZV5f8Fw',
    appId: '1:564628828414:ios:9e32fbbf72201cc9e635af',
    messagingSenderId: '564628828414',
    projectId: 'sanofinalproject',
    storageBucket: 'sanofinalproject.firebasestorage.app',
    iosBundleId: 'com.example.sanoFinalProject',
  );
}
